翻訳: WCAG 2.2 関連文書、WCAG 2.2 の要件
waic/wcag22 pull request #32
Opened 2023-11-17 01:19 UTC by tsmd

closes #4

2023-11-17 12:47 UTC, momdo requested changes
@tsmd 
ありがとうございます。2点ほどコメントしましたのでご確認ください。

2023-11-17 12:47 UTC, momdo commented on guidelines/index.html
> +            <p>WCAG 2.2 は、過去の WCAG 2 バージョン群の要件を継承する一連の <a href="https://w3c.github.io/wcag/requirements/22/">WCAG 2.2 の要件</a>を満たしている。要件は、ガイドラインの全体的なフレームワークを構成し、後方互換性を確保している。ワーキンググループはまた、達成基準のスタイルや品質が
リンクは原文に戻しておくとして、以下はいかがでしょうか

```suggestion
            <p>WCAG 2.2 は、以前の WCAG 2 のバージョンから要件を継承する一連の <a href="https://w3c.github.io/wcag/requirements/22/">requirements for WCAG 2.2</a> を満たしている。要件は、ガイドラインの全体的なフレームワークを構成し、後方互換性を確保している。ワーキンググループはまた、達成基準のスタイルや品質が WCAG 2.0 のものと類似することを確保するために、達成基準に対し、あまり形式的ではない一連の受け入れ基準を採用した。これらの要件は、WCAG 2.2 に含めることができるものを制限している。この制限は、WCAG 2 のドットリリースの性質を保持するために重要である。</p>
```

2023-11-17 12:47 UTC, momdo commented on guidelines/index.html
> +               <li><p><strong><a href="https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/">What's New in WCAG 2.2</a></strong> では、アクセシビリティの課題を示すペルソナの引用を交えて、新しい達成基準を紹介している。</p>
辞書寄りの翻訳にした以下はどうでしょうか。

```suggestion
               <li><p><strong><a href="https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/">What's New in WCAG 2.2</a></strong> では、アクセシビリティの問題を説明するペルソナの引用とともに、新しい達成基準を紹介している。</p>
```

2023-11-20 01:04 UTC, tsmd commented on guidelines/index.html
> +            <p>WCAG 2.2 は、過去の WCAG 2 バージョン群の要件を継承する一連の <a href="https://w3c.github.io/wcag/requirements/22/">WCAG 2.2 の要件</a>を満たしている。要件は、ガイドラインの全体的なフレームワークを構成し、後方互換性を確保している。ワーキンググループはまた、達成基準のスタイルや品質が
なるほど、「以前の」とすればすっきりしますね。イイと思います！

2023-11-20 01:05 UTC, tsmd commented on guidelines/index.html
> +               <li><p><strong><a href="https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/">What's New in WCAG 2.2</a></strong> では、アクセシビリティの課題を示すペルソナの引用を交えて、新しい達成基準を紹介している。</p>
違和感ありません。イイと思います！

2023-11-22 00:20 UTC, momdo commented
@tsmd 
確認ありがとうございます。

@bakera 
レビューをお願いします。

2023-11-22 00:21 UTC, momdo approved these changes

2023-12-17 11:54 UTC, bakera reviewed
細かいですが一箇所気になったのでコメントしました。

2023-12-17 11:54 UTC, bakera commented on guidelines/index.html
> +               <li><p><strong><a href="https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/">What's New in WCAG 2.2</a></strong> では、アクセシビリティの問題を説明するペルソナの引用とともに、新しい達成基準を紹介している。</p>
「ペルソナの引用」は普通に読むと「ペルソナ*を*引用している」と読めると思うのですが、ここでは "persona quotes..." であり「ペルソナ*が*引用している」という文です。もっとも、ここのquoteはいわゆる引用 (どこかに掲載されているものを引用してきている) とは違うように思います。紹介する、引き合いに出す、言及するというニュアンスに近いのではないでしょうか。

動詞のillustrateも訳しにくくて悩ましいのですが、"quote that illustrate X" 全体をざっくりと「Xの例を紹介する」としてしまってはどうでしょうか。……と思ったら introduce があって紹介かぶりになるので、紹介→説明ですかね。実際、リンク先ではペルソナさんが「I can't tell ...」などと発言している体裁で書かれているので、説明でも良いかなと。

たとえばこんな感じ?

```suggestion
               <li><p><strong><a href="https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/">What's New in WCAG 2.2</a></strong> では、アクセシビリティ問題の例を説明するペルソナともに、新しい達成基準を紹介している。</p>
```

2023-12-24 12:19 UTC, tsmd commented on guidelines/index.html
> +               <li><p><strong><a href="https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/">What's New in WCAG 2.2</a></strong> では、アクセシビリティの問題を説明するペルソナの引用とともに、新しい達成基準を紹介している。</p>
訳出が難しい文章でしたね・・・
persona quotesはやはり「ペルソナへの言及」であって、ペルソナ*が*言及しているという文章ではないように思いつつ、最終的な翻訳は太田さんの案でしっくりきました。
さすがです。ありがとうございます！

2023-12-26 12:06 UTC, bakera approved these changes
ありがとうございます。よさそうです。

2023-12-26 12:06 UTC, merged