WCAG 2.1 との比較
waic/wcag22 pull request #35
Opened 2023-11-26 01:02 UTC by tsmd

2023-11-26 04:49 UTC, momdo requested changes
@tsmd 
いろいろと手を加えてしまいましたがご検討ください。

2023-11-26 04:49 UTC, momdo commented on guidelines/index.html
> +               <p>WCAG 2 系のバージョンに対する後方互換性が重要となる開発者の混乱を招くことを避けるため、WCAG 2.2 における新しい達成基準はガイドライン内の一連の達成基準の末尾に追加されている。これにより、ガイドラインの既存の達成基準の間に新しい達成基準を挿入することによって生じるであろう、WCAG 2.1 からある達成基準のセクション番号の変更の必要性が、回避さ
```suggestion
               <p>WCAG 2 系のバージョンに対する後方互換性が重要となる開発者の混乱を招くことを避けるため、WCAG 2.2 における新しい達成基準はガイドライン内の一連の達成基準の末尾に追加されている。これにより、ガイドラインの既存の達成基準の間に新しい達成基準を挿入することによって生じるであろう、WCAG 2 からある達成基準のセクション番号を変更する必要がなくなる。しかしながらこのことは、各ガイドライン内の達成基準がもはや適合レベルごとにグループ化されていないことを意味する。各ガイドライン内での達成基準の順番は、適合レベルに関する情報を暗示するものではなく、各達成基準自身の適合レベル表示 (A / AA / AAA) のみが適合レベルを示す。<a href="https://www.w3.org/WAI/WCAG22/quickref/">WCAG 2.2 Quick Reference</a> は、他の多数のフィルター及び並べ替え方法とともに、適合レベルごとにグループ化された達成基準を見る方法を提供するだろう。</p>
```

「とともに」 [公⽤⽂における漢字使⽤等について](https://www.bunka.go.jp/kokugo_nihongo/sisaku/joho/joho/kijun/sanko/koyobun/pdf/kunrei.pdf)

少し変更しました。以下については手を入れていません。

- implementersは実装者のほうがよい？
- willを活かすなら、「は」を「が」に変えるのが適当かもしれない？

2023-11-26 04:49 UTC, momdo commented on guidelines/index.html
> +               <p>WCAG 2.2 は WCAG 2.0 と同様の適合モデルを使用している。これは WCAG 2.2 に適合するサイトが WCAG 2.0 及び WCAG 2.1 にも適合することを意図している。つまり、それらのサイトが WCAG 2.0 又は WCAG 2.1 を参照するいかなる方針の要件も満たすと同時に、現在のウェブ上の利用者のニーズをより良く満たすことを意
policyが「ポリシー」と「方針」で揺れている気がしますね…。
「いかなる」→「あらゆる」は趣味です

```suggestion
               <p>WCAG 2.2 は WCAG 2.0 と同様の適合モデルを使用している。これは WCAG 2.2 に適合するサイトが WCAG 2.0 及び WCAG 2.1 にも適合することを意図している。つまり、それらのサイトが WCAG 2.0 又は WCAG 2.1 を参照するあらゆる方針の要件も満たすと同時に、現在のウェブ上の利用者のニーズをより良く満たすことを意味する。</p>
```

2023-12-07 10:18 UTC, momdo commented on guidelines/index.html
> +            <p>WCAG 2.2 は、認知または学習障害のある利用者、ロービジョンの利用者、及びモバイルデバイス上の障害のある利用者、という三つの主要なグループのためのアクセシビリティのガイダンスを改善する WCAG 2.1 の取組を継続することを目的に開始された。これらのニーズを満たすために多くの方法が提案され評価され、ワーキンググループによって洗練された。WCAG 2.0 から
@tsmd 
WCAG 2.1訳が確定したので、それにあわせていただければと。。

2023-12-11 01:08 UTC, tsmd commented
@momdo 改めてレビューおねがいいたします！

2023-12-16 06:41 UTC, momdo reviewed
@tsmd 
ありがとうございます。よさそうです！

2023-12-16 06:42 UTC, momdo approved these changes

2023-12-21 05:57 UTC, bakera commented on guidelines/index.html
> +               <p>WCAG 2 系のバージョンに対する後方互換性が重要となる実装者の混乱を招くことを避けるため、WCAG 2.2 における新しい達成基準はガイドライン内の一連の達成基準の末尾に追加されている。これにより、ガイドラインの既存の達成基準の間に新しい達成基準を挿入することによって生じるであろう、WCAG 2 からある達成基準のセクション番号を変更する必要がなくなる。し
「後方互換性が重要となる実装者の混乱を招くことを避ける」は「重要となる」がどこにかかるかわかりにくいように思いました (「重要となる実装者」「重要となる混乱」のように読める)。「後方互換性を重視する」というくらいでどうでしょうか。「混乱を招くことを避ける」は単に「混乱を避ける」で良いかも知れません (原文 avoid confusion なので)。

```suggestion
               <p>WCAG 2 系のバージョンに対する後方互換性を重視する実装者の混乱を避けるため、WCAG 2.2 における新しい達成基準はガイドライン内の一連の達成基準の末尾に追加されている。これにより、ガイドラインの既存の達成基準の間に新しい達成基準を挿入することによって生じるであろう、WCAG 2 からある達成基準のセクション番号を変更する必要がなくなる。しかしながらこのことは、各ガイドライン内の達成基準がもはや適合レベルごとにグループ化されていないことを意味する。各ガイドライン内での達成基準の順番は、適合レベルに関する情報を暗示するものではなく、各達成基準自身の適合レベル表示 (A / AA / AAA) のみが適合レベルを示す。<a href="https://www.w3.org/WAI/WCAG22/quickref/">WCAG 2.2 Quick Reference</a> が、他の多数のフィルター及び並べ替え方法とともに、適合レベルごとにグループ化された達成基準を見る方法を提供するだろう。</p>
```

2023-12-24 03:13 UTC, tsmd commented on guidelines/index.html
> +            <p>WCAG 2.2 は、WCAG 2.1 をベースに構築されており、WCAG 2.1 と後方互換性がある。そのため、WCAG 2.2 に適合しているウェブページは、少なくとも WCAG 2.1 に適合しているページと同程度にアクセシブルである。2.1 及び 2.0 をベースにした複数の要件が追加されている。WCAG 2.2 では、一つの達成基準 <a href="#p
これは今まで意識できていなかったなーとハッとしました・・・
確かに「一つ以上」は「one or more」ですもんね。

2023-12-24 03:14 UTC, tsmd commented on guidelines/index.html
> +               <p>WCAG 2.2 はまた、<a href="#privacy-summary">プライバシー</a>及び<a href="#security-summary">セキュリティ</a>に影響を与える可能性のある仕様の観点を詳細に説明する新しい章を導入している。</p>
なるほど、わかりやすいですね！
「detailing」のニュアンスをきちんと取るためにも、実際に追加されてる項目を踏まえてみるのも重要ですね。勉強になります。

2023-12-24 03:15 UTC, tsmd commented on guidelines/index.html
> +               <p>WCAG 2 系のバージョンに対する後方互換性が重要となる実装者の混乱を招くことを避けるため、WCAG 2.2 における新しい達成基準はガイドライン内の一連の達成基準の末尾に追加されている。これにより、ガイドラインの既存の達成基準の間に新しい達成基準を挿入することによって生じるであろう、WCAG 2 からある達成基準のセクション番号を変更する必要がなくなる。し
鮮やかで痺れました！！

2023-12-26 12:10 UTC, bakera approved these changes
ありがとうございます。よさそうです。

2023-12-26 12:10 UTC, merged