WCAG 2.2：達成基準 2.5.7 Dragging Movements の翻訳
waic/wcag22 pull request #39
Opened 2023-11-30 08:10 UTC by caztcha

達成基準 2.5.7 Dragging Movements を翻訳しました。

2023-12-01 12:03 UTC, momdo requested changes
@caztcha 

ご検討ください。（もともと埋まってた箇所もコメントしてしまっていますが…）

2023-12-01 12:03 UTC, momdo commented on guidelines/index.html
>      <div class="note" role="note" id="issue-container-generatedID-36"><div role="heading" class="note-title marker" id="h-note-36" aria-level="5"><span>注記</span></div><p class="">この要件は、ポインタの動作を解釈するウェ
これは多分、既存の訳（どこ）から持ってきていると思いますが、「や」がいるので手を加えておきましょう…

> This requirement applies to web content that interprets pointer actions (i.e. this does not apply to actions that are required to operate the user agent or assistive technology).

```suggestion
    <div class="note" role="note" id="issue-container-generatedID-36"><div role="heading" class="note-title marker" id="h-note-36" aria-level="5"><span>注記</span></div><p class="">この要件は、ポインタの動作を解釈するウェブコンテンツに適用される (すなわち、これはユーザエージェント又は支援技術の操作に必要なアクションには適用されない)。</p></div>
```

2024-01-17 08:13 UTC, caztcha commented
@momdo レビューありがとうございます！いただいた修正提案、確認の上、コミットしました。

2024-01-18 09:40 UTC, momdo approved these changes

2024-01-22 09:51 UTC, bakera approved these changes
よさそうです!

2024-01-22 09:51 UTC, merged