WCAG 2.2：達成基準 3.2.6 Consistent Help の翻訳
waic/wcag22 pull request #41
Opened 2023-12-01 09:13 UTC by caztcha

達成基準 3.2.6 Consistent Help を翻訳しました。

2023-12-03 07:12 UTC, momdo requested changes
@caztcha 
ありがとうございます。
コメントをそれぞれご確認ください。

2023-12-03 07:12 UTC, momdo commented on guidelines/index.html
> +  <div class="note" role="note" id="issue-container-generatedID-40"><div role="heading" class="note-title marker" id="h-note-40" aria-level="5"><span>注記 2</span></div><p class="">この達成基準における「他のページコンテン
thought of as ～（である）と考えられる
<https://eow.alc.co.jp/search?q=thought+of+as>

variation　差異
<https://eow.alc.co.jp/search?q=variation>

concerned with ～に関心がある　としてみました
<https://eow.alc.co.jp/search?q=concerned+with>

```suggestion
  <div class="note" role="note" id="issue-container-generatedID-40"><div role="heading" class="note-title marker" id="h-note-40" aria-level="5"><span>注記 2</span></div><p class="">この達成基準における「他のページコンテンツに対して相対的に同じ順序」は、ページが線形化されたときにコンテンツが順序付けられる方法と考えることができる。ヘルプのメカニズムの視覚的な位置は、同じページの差異 (例えば CSS のブレークポイント) に対してページ間で一貫している可能性が高い。利用者は、ページのズーム、ページの向きを変えるなどの変更を発生させることができ、これによって異なるページの差異を引き起こす可能性がある。この達成基準は、同じページの差異 (例えば、同じズームレベル、向き) で表示されるページ間の相対的な順序に関心がある。</p></div>
```

2024-01-17 08:20 UTC, caztcha commented on guidelines/index.html
> +        <li>人間がコンタクトする詳細情報</li>
contact details が「連絡先」なの、言われてみればたしかに、そうでした。ありがとうございます！

2024-01-17 08:27 UTC, caztcha commented
@momdo レビューありがとうございます！いただいた修正提案、確認の上、コミットしました。

2024-01-18 09:41 UTC, momdo approved these changes

2024-01-23 08:16 UTC, bakera reviewed
いくつか気になったところをコメントしました。悩ましいところも多いのでご意見いただければと!

2024-01-23 08:16 UTC, bakera commented on guidelines/index.html
> +  <div class="note" role="note" id="issue-container-generatedID-40"><div role="heading" class="note-title marker" id="h-note-40" aria-level="5"><span>注記 2</span></div><p class="">この達成基準における「他のページコンテン
how を「方法」とするのはわかりにくいかも。順序付けられる方法 → 並べ方 くらいでよくないでしょうか。

the same page variation →「同じページの差異」は誤訳に近い感じがします。同じページバリエーション、たとえばスマホ版ならスマホ版、PC版ならPC版という話ですね。
different page variation → 異なるページの差異も同じ話で、PC版→スマホ版のような変化が起きることを言っていますが、これを「異なるページの差異」とするのはわかりにくいように思います。

"5. Conformance"の中の5.2.2 Full pagesには以下のような注釈があって、

>A full page includes each variation of the page that is automatically presented by the page for various screen sizes (e.g. variations in a responsive Web page). 

ここにもvariationが登場していますがまさに同じものですね。これを今の2.1日本語訳ではこうしているので、

>ウェブページ全体には、様々な画面サイズ向けに自動的に提示される個々のウェブページのバリエーションを含む (例: レスポンジブウェブページのバリエーション)。ウェブページ全体が適合するためには、個々のバリエーションが適合するか、適合する代替版が必要である。

これと同様にカタカナの「バリエーション」で良いように思います。

たとえばこう?

```suggestion
  <div class="note" role="note" id="issue-container-generatedID-40"><div role="heading" class="note-title marker" id="h-note-40" aria-level="5"><span>注記 2</span></div><p class="">この達成基準における「他のページコンテンツに対して相対的に同じ順序」は、ページが線形化されたときのコンテンツの並べ方と考えることができる。ヘルプのメカニズムの視覚的な位置は、ページの同じバリエーション (例えば CSS のブレークポイント) に対してページ間で一貫している可能性が高い。利用者は、ページのズーム、ページの向きを変えるなどの変更を発生させることができ、これはページのバリエーションが変化するきっかけになる可能性がある。この達成基準で扱うのは、同じバリエーション (例えば、同じズームレベル、向き) で表示されるページ同士の間における、相対的な順序である。</p></div>
```

2024-01-23 08:23 UTC, caztcha commented on guidelines/index.html
> +  <p><a href="#dfn-web-page-s" class="internalDFN" data-link-type="dfn" id="ref-for-dfn-web-page-s-9" title="単一の URI から HTTP で得た埋め込まれていないリソースに加え、レンダリングに使われる、又はユーザエージェントがこのリソースと一緒にレンダリングすることを意図しているその他
なるほど！確かに、「何を」変更したかが伝わりにくくなっていました。

2024-01-23 08:29 UTC, caztcha commented on guidelines/index.html
> +        <li>人間の連絡メカニズム</li>
Understanding を見ると、Human contact と Human contact mechanism の例として、以下のように記載されているので、おっしゃるように「人間**への**連絡」でよいかと思います！

- Human contact details such as a phone number, email address, hours of operation.
- Human contact mechanism such as a messaging system, chat client, contact form, social media channel.

2024-01-23 08:40 UTC, caztcha commented on guidelines/index.html
> +        <li>セルフヘルプのオプション</li>
「人間への連絡」に対して「自己解決のためのオプション」ですね。たしかに、このほうがわかりやすいですね。

2024-01-23 08:41 UTC, caztcha commented on guidelines/index.html
> +        <li>完全に自動化された連絡メカニズム</li>
そう、この部分は、　Understanding を読まないとさっぱりなんですよね...

2024-01-23 08:50 UTC, caztcha commented
@bakera レビューありがとうございます。いずれのご指摘も、すっと腹落ちした感があるので、修正提案、ひととおりコミットしました。

2024-01-25 02:41 UTC, bakera approved these changes
ありがとうございます。よさそうです!

2024-01-25 02:41 UTC, merged