WCAG 2.2：達成基準 3.3.7 Redundant Entry の翻訳
waic/wcag22 pull request #43
Opened 2023-12-04 06:46 UTC by caztcha

達成基準 3.3.7 Redundant Entry を翻訳しました。

2023-12-04 09:57 UTC, momdo requested changes
@caztcha 

ありがとうございます。
コメントしましたのでご確認ください。

2023-12-04 09:57 UTC, momdo commented on guidelines/index.html
> +    <p>同一の<a href="#dfn-processes" class="internalDFN" data-link-type="dfn" id="ref-for-dfn-processes-2" title="ある活動を完了させるために必要な利用者の一連の動作。">プロセス</a>において再入力する必要がある、利用者によって以前に入力された、又は利用者に提供された情報は、以下のいず
Information previously 以下と
Information (中略) that is required 以下は
両方ともInformationに係っている…はずですので、以下はどうでしょうか。

```suggestion
    <p>以前に利用者によって入力された、又は利用者に提供された情報であって、同一の<a href="#dfn-processes" class="internalDFN" data-link-type="dfn" id="ref-for-dfn-processes-2" title="ある活動を完了させるために必要な利用者の一連の動作。">プロセス</a>において再入力する必要がある情報は、以下のいずれかである。</p>
```

2023-12-04 09:57 UTC, momdo commented on guidelines/index.html
> +    <p>ただし、以下の場合は例外とする。</p>
「以下」については https://webdesk.jsa.or.jp/pdf/dev/md_5652.pdf#page=117 ということらしいので
「例外」についてはWCAG 2の既存訳で「除く」としているので

```suggestion
    <p>ただし、次の場合は除く。</p> 
```

2023-12-04 09:57 UTC, momdo commented on guidelines/index.html
> +        <li>その情報がコンテンツの安全性を確保するために必要である。又は、</li>
ここは素直にセキュリティでよいのではないかなと。

```suggestion
        <li>その情報がコンテンツのセキュリティを確保するために必要である。又は、</li>
```

2023-12-04 09:57 UTC, momdo commented on guidelines/index.html
> +        <li>以前に入力された情報が無効である。</li>
「無効になっている」のほうがよいかもしれません…が大差ないでしょうか。

2024-01-18 08:00 UTC, caztcha commented on guidelines/index.html
> +    <p>ただし、以下の場合は例外とする。</p>
「ただし、次の場合は除く:」に修正します。
// 最後は、句点 (。) ではなく半角コロン。
// 既存の達成基準 (2.5.4 動きによる起動) でも、「except when:」の訳が「ただし、以下の場合は例外とする。」となっているので、併せて、修正します。

2024-01-18 08:17 UTC, caztcha commented on guidelines/index.html
> +        <li>以前に入力された情報が無効である。</li>
「is no longer invalid.」は、たしかに、「無効になっている」のほうがよいと思います。

[238e052](https://github.com/waic/wcag22/pull/43/commits/238e0526580568c59cef8d5f4d3015213646c9aa) で修正しました。

2024-01-18 08:20 UTC, caztcha commented
@momdo レビューありがとうございました。一通り確認し、修正しましたので、ご確認いただけますと幸いです。

2024-01-18 09:43 UTC, momdo approved these changes
@caztcha 
ありがとうございます。よさそうです。

@bakera 
よろしくお願いします。

2024-01-25 07:41 UTC, caztcha commented
2024-01-25 の WG4 定例会にて : 
Redundant Entry の entry は、input とのニュアンスの違いを出すために、「入力」ではなく「入力項目」とする。

2024-01-25 09:53 UTC, bakera commented on guidelines/index.html
> +    <p>以前に利用者によって入力された、又は利用者に提供された情報であって、同一の<a href="#dfn-processes" class="internalDFN" data-link-type="dfn" id="ref-for-dfn-processes-2" title="ある活動を完了させるために必要な利用者の一連の動作。">プロセス</a>において再入力する必要がある情報は
「利用者に提供された」は「利用者によって提供された」とも取れますが、ここでは "provided to the user" なので「利用者に対して提供された」という意味ですね。明確に書いたほうが良いように思います。

そして「以下の」は全体的に「次の」にしていたような。

こんな感じでしょうか?

```suggestion
    <p>以前に利用者によって入力された、又は利用者に対して提供された情報であって、同一の<a href="#dfn-processes" class="internalDFN" data-link-type="dfn" id="ref-for-dfn-processes-2" title="ある活動を完了させるために必要な利用者の一連の動作。">プロセス</a>において再入力する必要がある情報は、次のいずれかである。</p>
```

2024-01-25 10:00 UTC, bakera commented on guidelines/index.html
> +               <li><a href="#redundant-entry">3.3.7 冗長な入力 (A)</a></li>
```suggestion
               <li><a href="#redundant-entry">3.3.7 冗長な入力項目 (A)</a></li>
```

2024-01-25 10:00 UTC, bakera commented on guidelines/index.html
> +               <li><a href="#redundant-entry">3.3.7 冗長な入力 (A)</a></li>
```suggestion
               <li><a href="#redundant-entry">3.3.7 冗長な入力項目 (A)</a></li>
```

2024-01-26 07:54 UTC, caztcha commented
@bakera レビューありがとうございます。また、ひとつずつ修正提案にしていただき、ありがとうございます。ひととおり確認のうえ、コミットいたしました。

2024-01-26 11:28 UTC, bakera commented
ありがとうございます!
(そしてコンフリクトしている……)

2024-02-01 07:37 UTC, caztcha commented
目次部分について、main ブランチ側の内容をイキにする形で、コンフリクトを解消してみました。

2024-02-01 11:55 UTC, merged